--- Makefile_orig	2012-12-03 04:09:09.644543351 +0900
+++ Makefile	2012-12-03 04:02:02.364756300 +0900
@@ -1,5 +1,5 @@
 CXX ?= g++
-CFLAGS = -Wall -Wconversion -O3 -fPIC
+CFLAGS = -Wall -Wconversion -O3 -fPIC -fopenmp
 SHVER = 2
 OS = $(shell uname)
 
